from typing import Annotated

from . import RawData


class DirectPdDeltaProHeartbeatPack(RawData):
    model: Annotated[int, "B", "model"]
    err_code: Annotated[bytes, "4s", "errCode"]
    sys_ver: Annotated[bytes, "4s", "sysVer"]
    wifi_ver: Annotated[bytes, "4s", "wifiVer"]
    wifi_auto_rcvy: Annotated[int, "B", "wifiAutoRcvy"]
    soc: Annotated[int, "B", "soc"]
    watts_out_sum: Annotated[int, "H", "wattsOutSum"]
    watts_in_sum: Annotated[int, "H", "wattsInSum"]
    remain_time: Annotated[int, "i", "remainTime"]
    beep_mode: Annotated[int, "B", "beepMode"]
    dc_out_state: Annotated[int, "B", "dcOutState"]
    usb1_watts: Annotated[int, "B", "usb1Watts"]
    usb2_watts: Annotated[int, "B", "usb2Watts"]
    qc_usb1_watts: Annotated[int, "B", "qcUsb1Watts"]
    qc_usb2_watts: Annotated[int, "B", "qcUsb2Watts"]
    typec1_watts: Annotated[int, "B", "typec1Watts"]
    typec2_watts: Annotated[int, "B", "typec2Watts"]
    typec1_temp: Annotated[int, "B", "typec1Temp"]
    typec2_temp: Annotated[int, "B", "typec2Temp"]
    car_state: Annotated[int, "B", "carState"]
    car_watts: Annotated[int, "B", "carWatts"]
    car_temp: Annotated[int, "B", "carTemp"]
    standby_min: Annotated[int, "H", "standbyMin"]
    lcd_off_sec: Annotated[int, "H", "lcdOffSec"]
    lcd_brightness: Annotated[int, "B", "lcdBrightness"]
    chg_power_dc: Annotated[int, "I", "chgPowerDC"]
    chg_sun_power: Annotated[int, "I", "chgSunPower"]
    chg_power_ac: Annotated[int, "I", "chgPowerAC"]
    dsg_power_dc: Annotated[int, "I", "dsgPowerDC"]
    dsg_power_ac: Annotated[int, "I", "dsgPowerAC"]
    usb_used_time: Annotated[int, "I", "usbUsedTime"]
    usbqc_used_time: Annotated[int, "I", "usbqcUsedTime"]
    typec_used_time: Annotated[int, "I", "typecUsedTime"]
    car_used_time: Annotated[int, "I", "carUsedTime"]
    inv_used_time: Annotated[int, "I", "invUsedTime"]
    dc_in_used_time: Annotated[int, "I", "dcInUsedTime"]
    mppt_used_time: Annotated[int, "I", "mpptUsedTime"]

    reserved: Annotated[bytes, "2s", "reserved"]
    ext_rj45_port: Annotated[int, "B", "extRj45Port"]
    ext_3p8_port: Annotated[int, "B", "ext3p8Port"]
    ext_4p8_port: Annotated[int, "B", "ext4p8Port"]
    sys_chg_dsg_state: Annotated[int, "B", "sysChgDsgState"]
    wifi_rssi: Annotated[int, "B", "wifiRssi"]
    wireless_watts: Annotated[int, "B", "wirelessWatts"]
    screen_state: Annotated[bytes, "14s", "screenState"]

    ac_auto_config: Annotated[int, "B", "acAutoConfig"]
    min_ac_out_soc: Annotated[int, "B", "minAcOutSoc"]
    ac_out_pause: Annotated[int, "B", "acOutPause"]
    watth_is_config: Annotated[int, "B", "watthIsConfig"]
    backup_soc: Annotated[int, "B", "backupSoc"]
    hysteresis_add: Annotated[int, "B", "hysteresisAdd"]
    relay_switch_count: Annotated[int, "I", "relaySwitchCount"]
