from typing import Annotated

from .base import RawData


class DirectMpptHeartbeatPack(RawData):
    fault_code: Annotated[int, "I", "faultCode"]
    sw_ver: Annotated[int, "I", "swVer"]
    in_vol: Annotated[int, "I", "inVol"]
    in_amp: Annotated[int, "I", "inAmp"]
    in_watts: Annotated[int, "H", "inWatts"]
    out_vol: Annotated[int, "I", "outVol"]
    out_amp: Annotated[int, "I", "outAmp"]
    out_watts: Annotated[int, "H", "outWatts"]
    mppt_temp: Annotated[int, "H", "mpptTemp"]
    xt60_chg_type: Annotated[int, "B", "xt60ChgType"]
    cfg_chg_type: Annotated[int, "B", "cfgChgType"]
    chg_type: Annotated[int, "B", "chgType"]
    chg_state: Annotated[int, "B", "chgState"]
    dcdc_12v_vol: Annotated[int, "I", "dcdc12vVol"]
    dcdc_12v_amp: Annotated[int, "I", "dcdc12vAmp"]
    dcdc_12v_watts: Annotated[int, "H", "dcdc12vWatts"]
    car_out_vol: Annotated[int, "I", "carOutVol"]
    car_out_amp: Annotated[int, "I", "carOutAmp"]
    car_out_watts: Annotated[int, "H", "carOutWatts"]
    car_temp: Annotated[int, "H", "carTemp"]
    car_state: Annotated[int, "B", "carState"]
    dc24v_temp: Annotated[int, "H", "dc24vTemp"]
    dc24v_state: Annotated[int, "B", "dc24vState"]
    chg_pause_flag: Annotated[int, "B", "chgPauseFlag"]
    dc_dip_switch: Annotated[int, "B", "dcDipSwitch"]
    cfg_fast_chg_watts: Annotated[int, "H", "cfgFastChgWatts"]
    cfg_slow_chg_watts: Annotated[int, "H", "cfgSlowChgWatts"]
    cfg_dc_chg_current: Annotated[int, "I", "cfgDcChgCurrent"]
    beep_mode: Annotated[int, "B", "beepMode"]
    cfg_ac_enable: Annotated[int, "B", "cfgAcEnable"]
    cfg_ac_xboost: Annotated[int, "B", "cfgAcXboost"]
    cfg_ac_out_vol: Annotated[int, "I", "cfgAcOutVol"]
    cfg_ac_out_freq: Annotated[int, "B", "cfgAcOutFreq"]
    cfg_chg_watt: Annotated[int, "H", "cfgChgWatt"]
    ac_standby_mins: Annotated[int, "H", "acStandbyMins"]
    discharge_type: Annotated[int, "B", "dischargeType"]
    car_standby_min: Annotated[int, "H", "carStandbyMin"]
    power_standby_min: Annotated[int, "H", "powerStandbyMin"]
    screen_standby_min: Annotated[int, "H", "screenStandbyMin"]
