from typing import Annotated

from .base import RawData


class KT210SAC(RawData):
    mode: Annotated[int, "B", "mode"]
    sub_mode: Annotated[int, "B", "subMode"]
    set_temp: Annotated[int, "B", "setTemp"]
    fan_value: Annotated[int, "B", "fanValue"]
    env_temp: Annotated[float, "f", "envTemp"]
    temp_sys: Annotated[int, "B", "tempSys"]
    display_idle_time: Annotated[int, "H", "displayIdleTime"]
    display_idle_mode: Annotated[int, "B", "displayIdleMode"]
    time_en: Annotated[int, "B", "timeEn"]
    time_set_val: Annotated[int, "H", "timeSetVal"]
    time_remain_val: Annotated[int, "H", "timeRemainVal"]
    beep_enable: Annotated[int, "B", "beepEnable"]
    err_code: Annotated[int, "I", "errCode"]
    name: Annotated[bytes, "32s", "name"]
    ref_en: Annotated[int, "B", "refEn"]
    bms_pid: Annotated[int, "H", "bmsPid"]
    wte_fth_en: Annotated[int, "B", "wteFthEn"]
    temp_display: Annotated[int, "B", "tempDisplay"]
    power_mode: Annotated[int, "B", "powerMode"]
    power_src: Annotated[int, "B", "powerSrc"]
    psdr_pwr_watt: Annotated[int, "H", "psdrPwrWatt"]
    bat_pwr_watt: Annotated[int, "H", "batPwrWatt"]
    mptt_pwr_watt: Annotated[int, "H", "mpttPwrWatt"]
    bat_dsg_remain_time: Annotated[int, "I", "batDsgRemainTime"]
    bat_chg_remain_time: Annotated[int, "I", "batChgRemainTime"]
    bat_soc: Annotated[int, "B", "batSoc"]
    bat_chg_status: Annotated[int, "B", "batChgStatus"]
    outlet_temp: Annotated[float, "f", "outLetTemp"]
    mppt_work: Annotated[int, "B", "mpptWork"]
    bms_err: Annotated[int, "B", "bmsErr"]
    rgb_state: Annotated[int, "B", "rgbState"]
    water_value: Annotated[int, "B", "waterValue"]
    bms_bound_flag: Annotated[int, "B", "bmsBoundFlag"]
    bms_undervoltage: Annotated[int, "B", "bmsUndervoltage"]
    ver: Annotated[int, "B", "ver"]
    resv_u8: Annotated[bytes, "20s", "resvU8"]
